# whitelist
branches:
  only:
    - master
    - develop

language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - mv example_config.cfg config.cfg

install:
  - pip install python-telegram-bot
  - pip install requests

script:
  - python test.py
